const STORAGE_KEY = 'wikimemory.notes.v1';
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`);
const seedNotes = [
  { id: uid(), title: '위키메모리 사용법', content: '생각을 작은 문서로 남기고, 태그로 연결해 보세요. 나중에 검색하면 필요한 맥락까지 함께 찾을 수 있습니다.', tags: ['가이드'], favorite: true, updatedAt: Date.now() },
  { id: uid(), title: '아이디어 보관함', content: '좋은 아이디어는 완성되기 전에 먼저 기록한다. 제목은 구체적으로, 내용은 다음 행동이 보이게 작성하기.', tags: ['아이디어'], favorite: false, updatedAt: Date.now() - 86400000 }
];
let notes = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || seedNotes;
let selectedId = null, activeFilter = 'all', activeTag = null, query = '';
const $ = id => document.getElementById(id);
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(notes));
const escapeHtml = value => String(value || '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const formatDate = timestamp => { const d = new Date(timestamp), now = new Date(); if (d.toDateString() === now.toDateString()) return '오늘'; return `${d.getMonth()+1}월 ${d.getDate()}일`; };
function filteredNotes() { let result = [...notes]; if (activeFilter === 'favorite') result = result.filter(n => n.favorite); if (activeFilter === 'recent') result.sort((a,b) => b.updatedAt-a.updatedAt).splice(10); if (activeTag) result = result.filter(n => n.tags.includes(activeTag)); if (query) result = result.filter(n => `${n.title} ${n.content} ${n.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())); return result.sort((a,b) => b.updatedAt-a.updatedAt); }
function renderTags() { const counts = {}; notes.forEach(n => n.tags.forEach(t => counts[t] = (counts[t] || 0) + 1)); $('tagList').innerHTML = Object.entries(counts).sort().map(([tag,count]) => `<button class="tag ${activeTag === tag ? 'selected':''}" data-tag="${escapeHtml(tag)}">#${escapeHtml(tag)} <small>${count}</small></button>`).join('') || '<span style="color:#aaa;font-size:12px">아직 태그가 없습니다</span>'; document.querySelectorAll('[data-tag]').forEach(b => b.onclick = () => { activeTag = b.dataset.tag; activeFilter='all'; render(); }); }
function renderList() { const list = filteredNotes(); $('resultCount').textContent = `${list.length}개`; $('noteList').innerHTML = list.map(n => `<div class="note-card ${selectedId === n.id ? 'selected':''}" data-id="${n.id}"><div class="note-title"><span>${escapeHtml(n.title || '제목 없음')}</span><span class="star ${n.favorite?'on':''}">${n.favorite?'★':'☆'}</span></div><div class="note-excerpt">${escapeHtml(n.content || '내용 없음')}</div><div class="note-meta"><span>${formatDate(n.updatedAt)}</span>${n.tags[0] ? `<span class="mini-tag">#${escapeHtml(n.tags[0])}</span>`:''}</div></div>`).join(''); $('emptyState').classList.toggle('hidden', list.length > 0); document.querySelectorAll('.note-card').forEach(card => card.onclick = e => { if (e.target.classList.contains('star')) { const n=notes.find(x=>x.id===card.dataset.id); n.favorite=!n.favorite; save(); render(); return; } selectedId=card.dataset.id; render(); }); }
function renderEditor() { const n = notes.find(x => x.id === selectedId); if (!n) { $('editorPanel').innerHTML = '<div class="editor-empty"><div class="large-mark">✦</div><h2>문서를 선택하세요</h2><p>왼쪽 목록에서 문서를 열거나<br />새 문서를 만들어 지식을 쌓아보세요.</p><button class="outline-button" id="editorNewButton">+ 새 문서 만들기</button></div>'; $('editorNewButton').onclick = newNote; return; } $('editorPanel').innerHTML = `<div class="editor-content"><div class="editor-toolbar"><span style="color:#9a9d95;font-size:12px">마지막 수정 ${formatDate(n.updatedAt)}</span><div class="editor-toolbar-actions"><button class="small-button" id="favoriteButton">${n.favorite?'★ 즐겨찾기됨':'☆ 즐겨찾기'}</button><button class="small-button danger" id="deleteButton">삭제</button></div></div><input class="title-input" id="titleInput" value="${escapeHtml(n.title)}" placeholder="문서 제목" /><textarea class="content-input" id="contentInput" placeholder="내용을 기록하세요. 다른 문서로 연결할 키워드와 맥락을 함께 적어두면 좋아요.">${escapeHtml(n.content)}</textarea><div class="editor-footer"><input class="tag-input" id="tagInput" value="${escapeHtml(n.tags.join(', '))}" placeholder="태그 (쉼표로 구분)" /><button class="save-button" id="saveButton">저장하기</button></div></div>`; $('saveButton').onclick = () => { n.title=$('titleInput').value.trim() || '제목 없음'; n.content=$('contentInput').value.trim(); n.tags=$('tagInput').value.split(',').map(x=>x.trim()).filter(Boolean); n.updatedAt=Date.now(); save(); render(); toast('문서를 저장했습니다'); }; $('favoriteButton').onclick = () => { n.favorite=!n.favorite; save(); renderEditor(); renderList(); }; $('deleteButton').onclick = () => { if (confirm('이 문서를 삭제할까요?')) { notes=notes.filter(x=>x.id!==n.id); selectedId=null; save(); render(); toast('문서를 삭제했습니다'); } }; }
function render() { const title = activeTag ? `#${activeTag}` : activeFilter === 'favorite' ? '즐겨찾기' : activeFilter === 'recent' ? '최근 수정' : '모든 문서'; $('listTitle').textContent = title; $('allCount').textContent = notes.length; $('favoriteCount').textContent = notes.filter(n=>n.favorite).length; document.querySelectorAll('.nav-item').forEach(b => b.classList.toggle('active', b.dataset.filter===activeFilter && !activeTag)); renderTags(); renderList(); renderEditor(); }
function newNote() { const n={id:uid(),title:'',content:'',tags:[],favorite:false,updatedAt:Date.now()}; notes.unshift(n); selectedId=n.id; activeFilter='all'; activeTag=null; save(); render(); setTimeout(() => $('titleInput')?.focus(), 0); }
function toast(message) { $('toast').textContent=message; $('toast').classList.add('show'); setTimeout(()=>$('toast').classList.remove('show'), 1800); }
document.querySelectorAll('.nav-item').forEach(b => b.onclick=()=>{activeFilter=b.dataset.filter; activeTag=null; render();});
$('newNoteButton').onclick=$('emptyNewButton').onclick=$('editorNewButton').onclick=newNote;
$('searchInput').oninput=e=>{query=e.target.value; renderList();}; $('clearTag').onclick=()=>{activeTag=null; render();}; $('themeButton').onclick=()=>{document.body.classList.toggle('dark');}; document.addEventListener('keydown', e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('searchInput').focus();}}); render();
